### ISSUE TITLE
self._vk.error is not a function widgets.js

### ISSUE THREAD

**Issue by ProFiLeR4100** [ciricc/easyvk#15]
Hello, 
When I call something that uses widgets, then this happens.
![X6uHhvC6qQg](https://user-images.githubusercontent.com/9364958/65910781-0cdea300-e3d4-11e9-8127-11678fe97efb.jpg)

Looks like self._vk.error is self._vk._error

**Comment by ciricc** [comment]
Thank you for report! Bug fixed
