### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by v1adjkee666** [ciricc/easyvk#17]
При использовании нескольких групп, крашится из-за данной строки 
```
	groups: [
		{
			groupId: 1,
			secret: '1',
			confirmCode: '1'
		},
		{
			groupId: 2,
			secret: '2',
			confirmCode: '2'
		}
	]
```

https://github.com/ciricc/easyvk/blob/c51810632b8f154567675a7905ea06fcba022c5e/src/utils/callbackapi.js#L192

**Comment by ciricc** [comment]
Спасибо, пофиксил.

До выхода обновления вы можете воспользоваться оберткой easyvk().then(vk => vk.callbackAPI.listen())
На сколько мне известно, тогда ошибок не будет.
