### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Xset-s** [ciricc/easyvk#19]
Everyday i get the same error: 
```[VK ERROR] FetchError: network timeout at: https://lp.vk.com/wh179713434...```

Can you explain me, how to implement auto reconnect for bot longpoll?

**Comment by ciricc** [comment]
I will fix it in next release. Now you can use `connection.on('error')` for handle it. And automate reconnect yourself

**Comment by ciricc** [comment]
Try update to easyvk@2.6.1 and run it.
