### ISSUE TITLE
UnhandledPromiseRejectionWarning в audio.get при заданном offset

### ISSUE THREAD

**Issue by PurpleHorrorRus** [ciricc/easyvk#5]
При попытке задать offset > 0 выдаёт ошибку `UnhandledPromiseRejectionWarning`.

> (node:132) UnhandledPromiseRejectionWarning: Error
>     at Request.request.post [as _callback] (.......\node_modules\easyvk\src\utils\AudioAPI.js:397:23)
>     at Request.self.callback (.......\node_modules\request\request.js:185:22)
>     at Request.emit (events.js:189:13)
>     at Request.<anonymous> (.......\node_modules\request\request.js:1161:10)
>     at Request.emit (events.js:189:13)
>     at IncomingMessage.<anonymous> (.......\node_modules\request\request.js:1083:12)
>     at Object.onceWrapper (events.js:277:13)
>     at IncomingMessage.emit (events.js:194:15)
>     at endReadableNT (_stream_readable.js:1103:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Сам код:
```javascript
vk.http.loginByForm({
        cookies: __dirname + "/mycookies.json"
    }).then(({client: Client}) => {
        Client.audio.get({
            owner_id: -45703770,
            offset: 100, // Здесь
            playlist_id: -1
        }).then(({vkr}) => {
            for(song in vkr)
                songs.push(`[${song}] ${vkr[song].performer} - ${vkr[song].title}`);
        }).catch(err => console.log(err));
    }).catch(err => console.log(err));
```

**Comment by ciricc** [comment]
Скорее всего, это происходит из-за слишком большого количества запросов (2000 треков в твоем случае). 

В следующей версии исправлю, добавив параметр count (кастомный, к сожалению, во ВКонтакте нельзя указать count в запросе). Дело в том, что за один запрос перезагрузки аудио (получение всей информации о треке) можно обновить максимум 10 треков.

Вот и простая математика. На 2000 треков приходится 200 запросов сразу

```javascript
client.audio.get({
  owner_id: -45703770,
  offset: 100, // Здесь
  playlist_id: -1,
  count: 5
}).then(({ vkr }) => {
  console.log(vkr.length)
})
```

**Comment by ciricc** [comment]
Проблема исправлена в 2.2.17 версии. Необходимо обновиться

**Comment by PurpleHorrorRus** [comment]
Да, действительно, данная проблема исправлена, спасибо большое. Но сломался поиск (на 2.2.16 работает, перепроверил). Кстати говоря, мне удалось пофиксить пару багов с ним на 2.2.16, куда можно прислать решение?

**Comment by ciricc** [comment]
Отправьте в pull request. Спасибо
