### ISSUE TITLE
И ещё пара важных багов

### ISSUE THREAD

**Issue by PurpleHorrorRus** [ciricc/easyvk#7]
Снова привет. Пытаюсь исправить пару очень важных багов, но никак не получается. Первый баг связан с капчей. Сама капча ловится, но вот captchaHandler ни в какую не хочет вызываться. 
Код дефолтный из документации
```javascript
const captchaHandler = ({captcha_sid, captcha_img, resolve:solve, vk}) => {
    console.log(true);
}

easyvk({
    username: settings.username,
    password: settings.password,
    captchaHandler: captchaHandler
}).then((vk) => { }).catch(console.error)
```
Второй баг связан с `audio.get(),` аудиозаписи не получаются, если у пользователя есть хотя бы один плейлист (то есть, у владельца аккаунта всё нормально получается, даже если у него есть плейлисты. У другого пользователя треки нормально получаются, если у него нет плейлистов). 
UPD: Не знаю как, но оно починилось... Но getById() по-прежнему не работает

**Comment by ciricc** [comment]
Привет. С капчей подробнее можно? Не работает при авторизации? Или когда?

Метод `audio.getById()` может работать только с AudioItem (тем аудио, который был получен в процессе работы Easy VK). 

К сожалению, я пока что не нашел способа, как получить аудиозапись только по ее `ID` и `OWNER_ID` Поэтому метод требует дополнительные хеши (два хеша, которые получает в процессе поиска аудиозаписей). 

Видимо, это неточность в документации

**Comment by PurpleHorrorRus** [comment]
Да, при авторизации. Стёр все файлы сессии для повторной авторизации и не мог войти в аккаунт какое-то время (около часа) из-за капчи. Картинка и sid капчи приходят в ошибке, но captchaHandler не вызывается

**Comment by ciricc** [comment]
Исправлю. Проблема действительно есть. Пока что можно использовать easyvk().catch() для ловли капчи самостоятельно, если это важно

**Comment by ciricc** [comment]
Попробуй заюзать версию с ветки dev, проблема решилась?
Вроде я все поправил

**Comment by PurpleHorrorRus** [comment]
Я попробую, но не знаю как спровоцировать капчу.
И ещё, друг только что любезно предоставил свой аккаунт, говорит, у него не получаются его аудиозаписи. Я проверил, get() возвращает "Error: Empty error responded". На любом другом тестовом аккаунте работает. С чем это может быть связано?

**Comment by ciricc** [comment]
Мб у него нет аудиозаписей?

**Comment by PurpleHorrorRus** [comment]
Есть

**Comment by ciricc** [comment]
Можно связаться с тобой в ВК? https://vk.com/kinock
